[package]
name = "webapp"
version = "0.1.0"
authors = ["Ramsay <ramsayleung@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.5"
rocket_contrib = { version = "0.4.5", features = ["tera_templates"] }
rspotify = { path = "../..", features = ["client-ureq", "ureq-rustls-tls"] ,default-features = false}
